azure_instance_type_rancher:                                    <change me> Standard_DS3_v2 # Without SUSE Security install, choose Standard_DS2_v2
azure_instance_type_downstream:                                 <change me> Standard_DS2_v2
azure_node_username:                                            <change me> some-name
azure_prefix_for_resourcegroup:                                 <change me> some-unique-name
azure_creator_tag:                                              <name of creator> Luke Skywalker

name_cloud_provider:                                            azure # used in kubeconfig filenames
kubernetes_cluster_name:                                        <change me> rancher
downstream_kubernetes_cluster_name:                             <change me> downstream
kubeconfig_location:                                            ~/.kube

# https://artifacthub.io/packages/helm/cert-manager/cert-manager
cert_manager_version:                                           1.18.2

# https://artifacthub.io/packages/helm/rancher-stable/rancher
rancher_helm_repository:                                        https://releases.rancher.com/server-charts/stable
rancher_version:                                                2.12.1

# Kubernetes version to use for Rancher server cluster
# https://github.com/rancher/k3s/releases
rancher_kubernetes_version:                                     v1.33.4+k3s1
downstream_kubernetes_cluster_version:                          v1.33.4+k3s1

# https://artifacthub.io/packages/helm/neuvectorcharts/core
# https://artifacthub.io/packages/helm/neuvectorcharts/crd
install_suse_security:                                          true
suse_security_version:                                          5.4.6